services:
  webapp:
    image: fintachartsimg
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    # depends_on:
    #   - db

  # db:
    # image: sqlite:latest
    # environment:
    #   - SQLITE_FILE=app.db
    # volumes:
    #   - ./data:/data
    # command: sqlite3 /data/app.db

# volumes:
#   data:
